# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9-stretch
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "src/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd src && yarn install && npm run compile-prod

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "src/package.json" }}

      - save_cache:
          key: v1-repo-{{ .Revision }}
          paths:
            - ~/repo

  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/python:2.7.13

    working_directory: ~/repo/deploy

    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}

      - run:
          command: |
            sudo pip install -r requirements.txt

      - run:
          command: |
            sudo apt-get update
            sudo apt install rsync
            python docker_digitalocean.py
            #sh ssh_diag.sh


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - hold:
         type: approval
         requires:
           - build
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master


